Sud 71
balex89/sudoku-solver pull request #21
Opened 2021-04-16 19:19 UTC by KalinovSergey

2021-04-20 17:38 UTC, balex89 requested changes

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +                    exclude_set = alternatives[c]
Здесь не понятно. Либо мы ищем первое такое явление. Тогда нужен `break`. Либо их может быть много, тогда их как-то надо накапливать, обрабатывать в цикле (не рекомендую). Пока ни то ни сё.

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +            if len(exclude_set) > 0:     #если такое множество найдено, исключаем его из всех остальных клеток пачки
Вместо этого условия можно просто продолжить блок кода предыдущего условия

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +                        if grid[i][e].alternatives != exclude_set:
Достаточно второго условия из двух

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +                for e in range(9):
обычно для индексов итерации используются буквы из последовательности `i, j, k, n, m`

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +        circus = 0
`circus` это цирк. А ещё существования этой переменной ничем не оправдано, пока у нас нет логирования.

2021-04-20 17:38 UTC, balex89 commented on src/sudoku.py
> +                is_any_cell_solved |= self.exclude_equal_alternatives(self.__squares)
На лицо дублирование кода. Почему бы не применить цикл.

2021-04-22 06:43 UTC, KalinovSergey commented on src/sudoku.py
> +                        if grid[i][e].alternatives != exclude_set:
так а зачем что-то делать с клеткой, если она уже решена?

2021-04-22 06:47 UTC, KalinovSergey commented on src/sudoku.py
> +            if len(exclude_set) > 0:     #если такое множество найдено, исключаем его из всех остальных клеток пачки
так если это условие не выполняется, значит подходящий exclude_set не найден, и исполнять последующий блок не имеет смысла

2021-04-22 19:20 UTC, KalinovSergey commented on src/sudoku.py
> +                        if grid[i][e].alternatives != exclude_set:
Не достаточно: если клетка решена,то этот блок попытается исключить из нее exclude_set, а потом проверит, не решена ли клетка, а если решена (а она же решена), то получится бесконечный цикл.

2021-04-23 09:47 UTC, balex89 commented on src/sudoku.py
> +            if len(exclude_set) > 0:     #если такое множество найдено, исключаем его из всех остальных клеток пачки
В счетчике по определению не может быть элементов с количеством 0, а у решенных клеток `__alternatives` нулевой длинны. Поэтому:
```
if len(alternatives[c]) == count[c]:
    exclude_set = alternatives[c]
    for e in range(9):
        ...
```

2021-04-23 10:07 UTC, balex89 commented on src/sudoku.py
> +                        if grid[i][e].alternatives != exclude_set:
Согласен. Тогда просто объединить условия в одну строку.

2021-04-24 10:19 UTC, balex89 requested changes

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +    def __exclude_equal_alternatives__(self, grid_view):
Неверное именование приватного метода

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +            alternatives = Counter([grid_view[i][j].alternatives for j in range(9)])  # формируем словарь алтернативы в пачке(строка, столбец или квадрант):количество таких альтернатив в пачке
1. Нет необходимости оборачивать в список и занимать память, можно передавать генератор
```suggestion
            alternatives = Counter(grid_view[i][j].alternatives for j in range(9))  # формируем словарь альтернативы в пачке(строка, столбец или квадрант):количество таких альтернатив в пачке 
```
2. Не очень удачное именование счетчика. Нужно чтобы было понятно, что это именно счетчик идентичных альтернатив. Например `twin_alternatives_counter`
3. Опечатка в комментарии.

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +            exclude_set = set()
Атавизм

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +            for alternative in alternatives:
А вот здесь уже `alternatives` 
```suggestion
            for alternatives in twin_alternatives_counter:
```

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +                if len(alternative) == alternatives[alternative]:  # ищем множество для исключения (альтернативы длинной N в количестве N в одной пачке)
опечатка в комментарии

2021-04-24 10:19 UTC, balex89 commented on src/sudoku.py
> +                    exclude_set = alternative
Нефункциональное переименование

2021-04-28 08:07 UTC, KalinovSergey commented on src/sudoku.py
> +            exclude_set = set()
Атави́зм (от лат. atavus «отдалённый предок») — появление у данной особи признаков, свойственных отдалённым предкам, но отсутствующих у ближайших.

2021-04-28 08:16 UTC, KalinovSergey commented on src/sudoku.py
> +                    exclude_set = alternative
alternative in alternatives заменить на alternatives in twin_alternatives_counter, да?

2021-05-03 19:40 UTC, balex89 commented on src/sudoku.py
> +            exclude_set = set()
Обсуждаем строчку 20. Предварительное объявление exclude_set больше не требуется.

2021-05-03 19:44 UTC, balex89 commented on src/sudoku.py
> +                    exclude_set = alternative
Обсуждаем строчку 23. Здесь вводится дополнительная ссылка на существующий изменяемый объект. При этом ни одна из двух ссылок дальше по коду не меняется. Тогда зачем их две?

2021-05-04 10:03 UTC, balex89 requested changes

2021-05-04 10:03 UTC, balex89 commented on src/sudoku.py
> +    def _exclude_equal_alternatives(self, grid_view):
Неверное именование приватного метода. Названия приватных классовых методов и атрибутов [должны начинаться с двух андерскоров.](https://docs.python.org/3/tutorial/classes.html?highlight=class-private#private-variables)

2021-05-05 17:13 UTC, balex89 approved these changes

2021-05-05 17:14 UTC, merged