SUD-48 Add Sudoku.__Is_valid , Sudoku.__is_valid_cell_sequence
balex89/sudoku-solver pull request #26
Opened 2021-05-17 13:23 UTC by KalinovSergey

2021-05-17 20:36 UTC, balex89 requested changes
Текущая `master` не слита с этой веткой (ветка [начинается из SUD-77](https://github.com/balex89/sudoku-solver/network)). Это в том числе мешает видеть на вкладке _Files changed_ реальный набор изменений кода.

2021-05-17 20:36 UTC, balex89 commented on src/sudoku.py
> +        return grid_is_valid
Однострочный вариант решения:
```
return all(self.__is_valid_cell_sequence(item) for item in (*self.__rows, *self.__columns, *self.__squares))
```
Но он не годится на перспективу с детализацией ошибки (не ясно, где клетка с ошибкой). А ещё в нём больше 100 символов!

Вариант без бинарной логики:
```
        for grid_view in (self.__rows, self.__columns, self.__squares):
            for item in grid_view:
                if not self.__is_valid_cell_sequence(item):
                    return False
        return True
```
Плюсы: 
1. Экономия числа итераций в цикле в случае ошибки
2. Минус одна переменная
3. Беглым взглядом сразу видно, какие значения метод возвращает

Также рекомендация по выбору из `tuple` и `list`: если и `tuple` и `list` одинаково подходят, всегда использовать `tuple`, т.к. он [немного оптимальнее](https://stackoverflow.com/questions/3340539/why-is-tuple-faster-than-list-in-python).

2021-05-20 07:08 UTC, KalinovSergey commented on src/sudoku.py
> +        if not(len(grid) == 9 and all([len(item) == 9 for item in grid])):
квадратные скобки убрал, но по второму пункту не понял что нужно делать( У меня вроде и так 2 условия: число строк равно 9 и все строки по 9 символов. Есди это не так - ошибка.

2021-05-20 18:43 UTC, balex89 commented on src/sudoku.py
> +        if not(len(grid) == 9 and all([len(item) == 9 for item in grid])):
```suggestion
        if len(grid) != 9 or any(len(item) != 9 for item in grid):
```

2021-05-20 19:23 UTC, balex89 commented on src/sudoku.py
> +        if not(len(grid) == 9 and all([len(item) == 9 for item in grid])):
или добавить функцию `is_valid_grid(grid)` и потом `if not is_valid_grid(grid):`

2021-05-23 19:15 UTC, balex89 requested changes

2021-05-23 19:15 UTC, balex89 commented on src/sudoku.py
> +    def __is_valid_grid(self, grid):                # проверка что сетка 9 на 9
Как минимум это `staticmethod` . А ещё лучше вынести в `utils`.

2021-05-23 19:15 UTC, balex89 commented on src/sudoku.py
> +            raise ValueError('Incorrect grid. Excepted grid 9x9')
```suggestion
            raise ValueError('Incorrect grid. Expectded grid 9x9')
```

2021-05-23 19:27 UTC, KalinovSergey commented on src/sudoku.py
> +            raise ValueError('Incorrect grid. Excepted grid 9x9')
"Expectded"  - тоже с опечаткой :)) какое трудное слово :))

2021-05-23 21:09 UTC, balex89 approved these changes

2021-05-23 21:13 UTC, merged