SUD-76 Add test_sudoku_EEA
balex89/sudoku-solver pull request #27
Opened 2021-05-23 07:29 UTC by KalinovSergey

2021-05-23 20:59 UTC, balex89 requested changes

2021-05-23 20:59 UTC, balex89 commented on tests/test_sudoku.py
> +    s = Sudoku(EEA_TASK)
Принцип юнит-тестирования в том, чтобы _изолированно_ проверять работу отдельный функциональных частей кода, не затрагивая лишние. На самом деле метод `__exclude_equal_alternatives` должен быть статическим. А значит не требует создания объекта `Sudoku` вообще. 
Итого:

1. Сделать `__exclude_equal_alternatives` статическим
1. Добавить на уровень модуля функцию `_cell_from_alternatives(alternatives: Iterable) -> Cell` которая создаёт объект `Cell` c заданным набором альтернатив.
1. Внутри `test_exclude_equal_alternatives` создать `grid_view` как список списков объектов `Cell` с заданными альтернативами. Передать `grid_view` в метод. (Объект Sudoku создавать не нужно) 
1. Проверить, что вернул метод. Проверить как изменились `.__alternatives` у элементов `grid_view`.

2021-05-23 20:59 UTC, balex89 commented on tests/test_sudoku.py
> +def test_sudoku_EEA():
название автотеста обычно содержит название тестируемого метода.  Так легче читать логи тестирования. А слово `sudoku` уже содержится в названии модуля.
```suggestion
def test_exclude_equal_alternatives():
```

2021-05-24 19:04 UTC, KalinovSergey commented on tests/test_sudoku.py
> +    s = Sudoku(EEA_TASK)
а если немного по-другому:
сначала создаю список списков из пустых Cell'ов, алтернативы у них одинаковые  от 1 до 9,
а потом для первой строки задаю нужные альтернативы, т.е. _cell_from_alternatives(alternatives: Iterable) -> Cell не нужна.

2021-05-26 12:37 UTC, balex89 requested changes

2021-05-26 12:37 UTC, balex89 commented on tests/test_sudoku.py
> +    grid_view = [[_cell_from_alternatives(EEA_1ST_ROW_ALTERNATIVES[i]) if j == 0 else _cell_from_alternatives() for i in range(9)] for j in range(9)]
```suggestion
    grid_view = [[_cell_from_alternatives(EEA_1ST_ROW_ALTERNATIVES[i] if j == 0 else None) for i in range(9)] for j in range(9)]
```

2021-05-26 12:37 UTC, balex89 commented on tests/test_sudoku.py
> +    assert [[cell.value for cell in row] for row in grid_view] == EEA_SOLUTION
1. Зачем проверять все 9 строк, если хотим проверить только первую? 
2. Почему проверяем `value` а не `alternatives`? Это противоречит назначению метода, метод не обязательно решает клетки, он исключает альтернативы. Кстати. поэтому для большего охвата теста можно и входные данные изменить
```
EEA_1ST_ROW_ALTERNATIVES = [
    {1, 2, 3, 4},
    {1, 2, 3, 4},
    {1, 2, 3, 4},
    {1, 2, 3, 4},
    {1, 2, 3, 4, 5, 6},
    {1, 2, 3, 4, 6, 5},
    {1, 2, 3, 4, 7},
    {1, 2, 3, 4, 8},
    {1, 2, 3, 4, 9}
    ]
```

2021-05-29 07:04 UTC, KalinovSergey commented on tests/test_sudoku.py
> +    grid_view = [[_cell_from_alternatives(EEA_1ST_ROW_ALTERNATIVES[i]) if j == 0 else _cell_from_alternatives() for i in range(9)] for j in range(9)]
наверное вместо None должно быть Cell()?, т.к. grid_view  это должнабыть сетка  из Cell'ов

2021-05-29 07:09 UTC, KalinovSergey commented on tests/test_sudoku.py
> +    assert [[cell.value for cell in row] for row in grid_view] == EEA_SOLUTION
1. Зачем проверять все 9 строк, если хотим проверить только первую? - Потому что метод __exclude_equal_alternatives принимает аргумент грид 9 на 9. Если передать пачку, то будет out of index здесь:
for i in range(9):
            twin_alternatives_counter = Counter(grid_view[i][j].alternatives for j in range(9))

2021-05-29 07:17 UTC, KalinovSergey commented on tests/test_sudoku.py
> +    assert [[cell.value for cell in row] for row in grid_view] == EEA_SOLUTION
В 5 элементе EEA_1ST_ROW_ALTERNATIVES предлагаю установить {1, 2, 3, 4, 5} что бы хотя бы в одной клетке проверить что она решена

2021-05-31 15:47 UTC, balex89 requested changes

2021-05-31 15:47 UTC, balex89 commented on tests/test_sudoku.py
> +    assert [[cell.value for cell in row] for row in grid_view] == EEA_SOLUTION             # проверяем value во всем гриде: в первой строке 5-ая клетка решена, в других строках value не изменились и
То, что клетка решается, когда у неё остаётся 1 альтернатива это логика Cell и проверяется в модуле тестов Cell. Здесь нужно проверить только состояние альтернатив, потому что метод работает с альтернативами.
```suggestion
```

2021-05-31 15:47 UTC, balex89 commented on tests/test_sudoku.py
> +    assert all([grid_view[i][j]._Cell__alternatives == {1, 2, 3, 4, 5, 6, 7, 8, 9} for j in range(9)] for i in range(1,9)) # проверяем, что альтернативы в других строках не изменлись
А вот это правильно 👍

2021-06-07 09:08 UTC, balex89 commented on tests/test_sudoku.py
> +    grid_view = [[_cell_from_alternatives(EEA_1ST_ROW_ALTERNATIVES[i]) if j == 0 else _cell_from_alternatives() for i in range(9)] for j in range(9)]
Здесь None это аргумент `_cell_from_alternatives`, но можно и так

2021-06-07 09:11 UTC, balex89 approved these changes

2021-06-07 09:20 UTC, merged