WIP: SUD-88 Add Sudoku().is_solved, InvalidSudokuException, self._speculat…
balex89/sudoku-solver pull request #31
Opened 2021-06-10 08:13 UTC by KalinovSergey

…ion_depth

2021-06-11 08:01 UTC, balex89 submitted a review, later dismissed

2021-07-19 10:28 UTC, balex89 requested changes

2021-07-19 10:28 UTC, balex89 commented on src/sudoku.py
> +                    sudoku_copy.__rows[i][j].value = alternatives.pop()
Есть уязвимость, связанная с будущим авто-тестированием и отладкой функционала, в котором есть элемент случайности, т.к. `set.pop()` не предсказуем. Предлагаю заменить на `list.pop()`
```suggestion
                alternatives = sorted(self.__rows[i][j].alternatives)
                while len(alternatives) > 0:
                    sudoku_copy = copy.deepcopy(self)
                    sudoku_copy._speculation_depth += 1
                    sudoku_copy.__rows[i][j].value = alternatives.pop()
```

2021-07-19 10:28 UTC, balex89 commented on tests/test_sudoku.py
> +from resources import EASY_TASK, EASY_SOLUTION, HARD_TASK, HARD_SOLUTION, HARD_TASK_2, HARD_TASK_2_SOLUTION, HARD_TASK_3, HARD_TASK_3_SOLUTION
Непоследовательное именование
```suggestion
from resources import EASY_TASK, EASY_SOLUTION, HARD_TASK, HARD_SOLUTION, HARD_TASK_2, HARD_SOLUTION_2, HARD_TASK_3, HARD_SOLUTION_3
```

2021-07-19 14:35 UTC, KalinovSergey commented on src/sudoku.py
> +                    sudoku_copy.__rows[i][j].value = alternatives.pop()
странное дело: в этом случае (alternatives = **sorted**(self.__rows[i][j].alternatives) трудное задание не решается.

2021-07-21 09:48 UTC, balex89 approved these changes

2021-07-21 09:57 UTC, merged