SUD-44 Add Sudoku.get_tesk() and test
balex89/sudoku-solver pull request #41
Opened 2021-10-27 06:58 UTC by KalinovSergey

2021-10-31 19:34 UTC, KalinovSergey commented on src/sudoku.py
> +            try:
возникают ошибки Empty alternatives before solution. Например если на сайте заполнять наобум сетку, то такая ошибка может возникать в валидной сетке.

2021-10-31 19:45 UTC, KalinovSergey commented
Переделал на хранение состояния сетки не в sudoku, а в гриде. Соответственно перед каждой попыткой решения создается объект sudoku. Пока оставил вспомогательные принты. В исключениях оставил только InvalidSudokuException, CellStateException. В результате где-то на 50-60 шаге возникает ошибка ValueError('Sudoku rules are violated') где-то в недрах __exclude_violating_alternative. Если вернуть на expect except Exception, то где-то 70-75 шаге просто виснет. Для сокращения времени уменьшил MAX_SPECULATION_DEPTH = до двух. Задание создается, но тоже очень долго, около 20 минут. В общем какая-то магия, не могу разобраться, давай вместе в понедельник посмотрим.

2021-11-13 21:06 UTC, balex89 commented
Закрываю до решения SUD-134

2021-11-25 17:51 UTC, balex89 requested changes

2021-11-25 17:51 UTC, balex89 commented on src/sudoku.py
> +    def get_task(self):
Предлагаю глубину сделать параметром метода, чтобы проще было им управлять

2021-11-25 17:51 UTC, balex89 commented on src/sudoku.py
> +            current_cell_copy = task[i][j]
Имена переменных следует адаптировать к изменениям логики.
```suggestion
            true_cell_value = task[i][j]
```

2021-11-25 17:51 UTC, balex89 commented on src/sudoku.py
> +                    except (Exception):
Слишком широкий класс исключений, нужно конкретизировать.
Избыточные скобки.

2021-11-25 18:37 UTC, balex89 approved these changes

2021-11-25 18:38 UTC, merged