SUD-134 Add Sudoku.burn_alternatives(), callback
balex89/sudoku-solver pull request #43
Opened 2021-11-14 13:55 UTC by KalinovSergey

2021-11-14 13:59 UTC, KalinovSergey commented
Заменил копирование объектов Sudoku с copy.deepcopy на создание нового объекта, т.к. при копировании коллбеки также копировались и ссылались клетки исходного судоку.

2021-11-14 19:22 UTC, balex89 requested changes

2021-11-14 19:22 UTC, balex89 commented on tests/test_sudoku.py
> +@pytest.mark.skip(reason="Alternative exclusion bug")
Причина не "Alternative exclusion bug". Этот баг решён.
На  самом деле мы утопаем в рекурсии потому, что существует слишком большое количество способов решить это задание. При этом, судя по всему, решений не так уж много, но способов их получить да.

Можно было бы принять подход: если встречаем хотя бы два разных способа решить задание -- отказываемся его решать.
Однако опыты показывают, что даже это не спасает. Цифр может быть меньше, при этом достаточно, чтобы погрузиться в рекурсию, но недостаточно чтобы найти хотя бы одно решение за разумное время. 
Наши классические подходы к решению с этим судоку не справятся.

Поэтому тест нужно пока оставить `mark.skip`. А `reason` я бы сформулировал так: 
```suggestion
@pytest.mark.skip(reason="Recursion calls take too much time")
```

2021-11-23 10:06 UTC, balex89 commented on src/cell.py
> +    def do_nothing():
Надо почистить do_nothing

2021-11-23 10:06 UTC, balex89 requested changes
Почистить do_nothing

2021-11-23 12:07 UTC, balex89 approved these changes

2021-11-23 12:11 UTC, merged