SUD-149 Fix EEA. Excluding alternatives in list of cell indexes
balex89/sudoku-solver pull request #47
Opened 2021-12-15 07:34 UTC by KalinovSergey

2021-12-15 10:28 UTC, balex89 requested changes
Добавить тест с примером, который раньше вызывал ошибку

2021-12-15 10:28 UTC, balex89 commented on src/sudoku.py
> +                        (not batch[index].is_solved and batch[index].alternatives != alternatives)]
1. Нет смысла материализировать список, достаточно создать генератор
2. Избыточные скобки в условии
3. Предлагаю утвердить стиль: 
```
# либо так
var = (expression expression
       expression expression)

# либо так
var = (
    expression expression
    expression expression
)

# но не так
var = (
    expression expression
    expression expression)
```

```suggestion
                    cell_indexes = (
                        index for index in range(9)
                        if not batch[index].is_solved and batch[index].alternatives != alternatives
                    )
```

2021-12-15 14:02 UTC, KalinovSergey commented on src/sudoku.py
> +                        (not batch[index].is_solved and batch[index].alternatives != alternatives)]
если вместо квадратных скобок сделать круглые, то снова возникает Empty alternatives before solution . Оставлю тогда квадратные

2021-12-16 15:51 UTC, balex89 commented
https://github.com/balex89/sudoku-solver/pull/47#pullrequestreview-832618830

2021-12-17 13:40 UTC, balex89 approved these changes

2021-12-17 13:41 UTC, merged