Sud 151 Set task difficult in Sudoku.get_task()
balex89/sudoku-solver pull request #50
Opened 2022-02-16 06:29 UTC by KalinovSergey

Пока оставил все вспомогательные переменные для сбора статистики. Потом, если будут не нужны, удалим.

2022-02-16 12:09 UTC, KalinovSergey commented
Я тут подумал, а может сделать функцию get_difficult, которая принимает грид и speculation_depth, решает его, и возвращает сумму LEA, EEA, EVA. А если грид не решен, то возвращает например -1?

2022-02-21 23:03 UTC, balex89 requested changes

2022-03-10 06:54 UTC, KalinovSergey commented on src/sudoku.py
> +            self._EEA_call += 1
а как для LEA и EEA получить значения счетчика?
Пробую так : s._counter[s._exclude_equal_alternatives].solved , но пишет ошибку:
File "C:\kss\sudoku-solver\sudoku-solver\src\counter.py", line 16, in __getitem__
    return self._method_counters.setdefault(item.__name__, self._MethodCounter())
AttributeError: 'functools.partial' object has no attribute '__name__'

2022-03-10 09:47 UTC, balex89 commented on src/sudoku.py
> +            self._EEA_call += 1
1. `__name__`, не `name` 
2. Действительно, всё немножко сложнее. Разберёмся подробнее: функция `_exclude_equal_alternatives()` оборачивается декоратором `_wrapped_in_method()`, и после оборачивания вернётся объект `functools.partialmethod()`. Это [дескриптор](https://docs.python.org/3/howto/descriptor.html), который для объекта Sudoku() "превратится" в `functools.partial()` (далее `item`). Получается, что 
а) у `item` (класса `partial`) нет атрибута имени
б) более того, этот `item` является обёрткой не для  `_exclude_equal_alternatives()`, а для `_apply_batch_method()`, то есть `item.func.__name__ == "_apply_batch_method"`.
Сама же функция `_exclude_equal_alternatives()` является первым **_аргументом_** `partial`-обёртки. Поэтому её можно получить как `item.args[0]`.

Итого:
```python
class _Counter:
    ...
    def __getitem__(self, item: Callable):
        name = (item.args[0] if isinstance(item, partial) else item).__name__
        return self._method_counters.setdefault(name, self._MethodCounter())
```

2022-03-11 18:59 UTC, KalinovSergey commented on src/sudoku.py
> +        self._burn_alternatives_solved = 0
А как же тогда разбивать длинную строку, если ни перед , ни после плюса нельзя?:

Run # stop the build if any pep8 rule violated (except complexity)
./src/sudoku.py:221:20: W503 line break before binary operator
                   + sudoku._counter[sudoku._exclude_equal_alternatives].solved) > max_difficulty:
                   ^
./src/sudoku.py:225:74: W504 line break after binary operator
            if (sudoku._counter[sudoku._leave_equal_alternatives].solved +
                                                                         ^
./tests/test_sudoku.py:[16](https://github.com/balex89/sudoku-solver/runs/5515572178?check_suite_focus=true#step:5:16)8:70: W504 line break after binary operator
    assert (sudoku._counter[sudoku._leave_equal_alternatives].solved +
                                                                     ^
1     W503 line break before binary operator
2     W504 line break after binary operator


Читал, вроде если внутри скобок разбиение, то должно быть ок.

2022-03-14 19:14 UTC, balex89 requested changes

2022-03-14 19:14 UTC, balex89 commented on src/sudoku.py
> +from counter import _Counter
отделить пустой строкой

2022-03-14 19:14 UTC, balex89 commented on src/sudoku.py
> +        self.rounds = 0
атрибут удалить

2022-03-14 19:14 UTC, balex89 commented on src/sudoku.py
> +                   + sudoku._counter[sudoku._exclude_equal_alternatives].solved) > max_difficulty:
```suggestion
                if not sudoku.is_solved or (
                    sudoku._counter[sudoku._leave_equal_alternatives].solved
                    + sudoku._counter[sudoku._exclude_equal_alternatives].solved
                ) > max_difficulty:
```

2022-03-15 19:17 UTC, KalinovSergey commented on src/sudoku.py
> +        self._burn_alternatives_solved = 0
оказалось, что нельзя просто взять и изменить файлы. На каждый файл получилось по пулреквесту.

2022-03-19 09:46 UTC, balex89 requested changes

2022-03-19 09:46 UTC, balex89 commented on src/sudoku.py
> +               ) >= min_difficulty:
Форматирование не хорошее.
Ещё разок возможные варианты:
```
foo = (foo bar
       + foo bar)
```
или
```
foo = (
    foo bar
    + foo bar
)
```


```suggestion
            if (
                sudoku._counter[sudoku._leave_equal_alternatives].solved
                + sudoku._counter[sudoku._exclude_equal_alternatives].solved
            ) >= min_difficulty:
```

2022-03-19 09:46 UTC, balex89 commented on tests/test_sudoku.py
> +           ) == 4
форматирование

2022-03-20 12:11 UTC, balex89 approved these changes

2022-03-20 12:13 UTC, merged