SUD-166 Add route /v1/task_difficulty and test
balex89/sudoku-solver pull request #53
Opened 2022-03-20 19:06 UTC by KalinovSergey

2022-03-28 09:44 UTC, balex89 requested changes

2022-03-28 09:44 UTC, balex89 commented on src/app/routes.py
> +def get_task_difficulty():
```suggestion
def get_custom_task():
```

2022-03-28 09:44 UTC, balex89 commented on src/app/routes.py
> +    max_difficulty = int(request.args["max_difficulty"])
```suggestion
    min_difficulty = int(request.args["min_difficulty"])
    max_difficulty = int(request.args["max_difficulty"])
    logger.info("Generating task with min_difficulty = %s, max_difficulty = %s", min_difficulty, max_difficulty )
```

А что, если какой-то из параметров не будет передан? Обязательны ли эти границы?

2022-03-28 12:46 UTC, KalinovSergey commented on src/app/routes.py
> +    max_difficulty = int(request.args["max_difficulty"])
Так этот запрос как раз предназначен для выдачи задания определенной сложности. Если без параметров, то нужно использовать get_task

2022-03-28 18:48 UTC, balex89 commented on src/app/routes.py
> +    max_difficulty = int(request.args["max_difficulty"])
Да, но в то же время `Sudoku.get_task()` позволяет опускать одну из или обе границы. А этот метод не позволяет.

2022-04-01 16:05 UTC, balex89 approved these changes

2022-04-01 16:05 UTC, merged